[project]
name = 'Tokenized-Environmental-Restoration-Marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.funding-coordination]
path = 'contracts/funding-coordination.clar'
clarity_version = 2
epoch = 2.5

[contracts.impact-quantification]
path = 'contracts/impact-quantification.clar'
clarity_version = 2
epoch = 2.5

[contracts.outcome-verification]
path = 'contracts/outcome-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
